language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules
script:
  - cd react-app && yarn install && yarn build
  - npm test -- --coverage
after_script:
  - npm run codecov